### PR TITLE
Specify workspace directory

### PR DESCRIPTION
**Pull request by Tgjmjgj**
This is a feature mentioned in this Issue: https://github.com/actions/npm/issues/22
I added the `DIR` environment variable to specify a directory in which all commands will be executed.
This variable is checked and used in the `entrypoint.sh` script.
Also, I added the bats test and a full feature description with an example in README.md.

### CODE REVIEW

**Comment by saravankumarpa** [comment]
Is there a way  I can use this now before it get merged ?

**Comment by Tgjmjgj** [comment]
@saravankumarpa Yes, you can use my fork for now. Like in this example:
```
action "Install dependencies" {
  uses = "Tgjmjgj/npm@specify-workspace-directory"
  args = "install"
  env = {
    DIR = "./functions"
  }
}

**Comment by saravankumarpa** [comment]
> @saravankumarpa Yes, you can use my fork for now. Like in this example:
> 
> ```
> action "Install dependencies" {
>   uses = "Tgjmjgj/npm@specify-workspace-directory"
>   args = "install"
>   env = {
>     DIR = "./functions"
>   }
> }
> ```

thanks..waiting for this to get merged

**Comment by xt0rted** [comment]
Once you're on v2 of the actions preview this action shouldn't be needed anymore. You can use the new [setup-node](https://github.com/actions/setup-node) action along with a script task and the [`working-directory`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory) setting. This would result in a config along the lines of:

```yaml
steps:
  - uses: actions/setup-node@v1
    with:
      version: '12.x'

  - run: npm ci
    working-directory: src/website

  - run: npm test
    working-directory: src/website
```

**Comment by Tgjmjgj** [comment]
@xt0rted Oh, thanks, I haven't watched the new version yet. It seems really powerful compared to v1.

**Comment by chrispat** [comment]
This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum https://github.community/t5/GitHub-Actions/bd-p/actions.

**Pull request closed without merging**
